#!/usr/bin/env ruby

if ARGV[0] == 'get'
  # hack to download input
  now = Time.now.utc - 5*60*60
  year, day = now.year, (ARGV[1] || now.day)
  out = "%4d/input/%02d" % [year, day]

  unless File.exist?(out)
    url = "https://adventofcode.com/%d/day/%d/input" % [year, day]
    puts "> curl #{url}"
    session = File.read(".session")
    `curl -o #{out} -b session=#{session} #{url}`
  end

  exit
end

## ARGV can be provided in any order, [year, day, lang] being distinct.

# Extract language, default all
lang = ARGV.detect{|v| v =~ /[a-z]+/}
ARGV.delete(lang)
lang ||= '*'

# Extract year, default latest
year = ARGV.detect{|v| v =~ /\A2[0-9]{3}\z/}
ARGV.delete(year)
year ||= Dir["20*"].last

# Extract day, default whole-year
day = ARGV.detect{|v| v =~ /\A\d?\d\z/}
day = "0#{day}" if day && day.to_i < 10
day = "*" if day.nil?

def run(script)
  year, lang, _file = script.split('/')

  output = case lang
  when 'nim'
    # Redirecting stderr to strip build debug output
    # Building in release mode for performance
    `nim c --hints=off -p=lib/nim -d=release #{script}`
    `#{script.split('.')[0]}`
  when 'ruby'
    `ruby -Ilib/ruby -I#{year}/#{lang} #{script}`
  else
    return nil
  end

  output.chomp.split("\n")
end

Dir["#{year}/#{lang}/*#{day}*.*"].sort.each do |script|
  start = Time.now
  solution, solution2 = run(script)
  stop = Time.now
  duration = stop-start
  next if solution.nil?

  puts "(%5.2fs) %-20s %-10s %-10s" % [duration, script, solution, solution2]
end
