#!/usr/bin/env ruby
require "fileutils"

begin
  require "concurrent"
  require "concurrent-edge" # for Throttle
rescue LoadError
  puts "Please install the concurrent-ruby and concurrent-ruby-edge gems."
  exit
end

if ARGV[0] == "get"
  require "tzinfo"

  AOC_TIMEZONE = TZInfo::Timezone.get("US/Eastern")
  AOC_OFFSET = AOC_TIMEZONE.current_period.utc_total_offset / 60 / 60

  # hack to download input
  now = Time.now.getlocal("%+.2d:00" % AOC_OFFSET)
  year, day = (ARGV[2] || now.year), (ARGV[1] || now.day)
  out = "%4d/%02d/input" % [year, day]

  if File.exist?(out)
    day += 1
    out = "%4d/%02d/input" % [year, day]
  end
  FileUtils.mkdir_p("%4d/%02d" % [year, day])

  unless File.exist?(out)
    url = "https://adventofcode.com/%d/day/%d/input" % [year, day]

    date = "%4d-12-%02d" % [year, day]
    print "Waiting for #{date}" if now.strftime("%Y-%m-%d") < date
    loop do
      now = Time.now.getlocal("%+.2d:00" % AOC_OFFSET)
      break if now.strftime("%Y-%m-%d") >= date
      print "."
      sleep 1
    end

    puts "> curl #{url}"
    session = File.read(".session")
    `curl -o #{out} -b session=#{session} #{url}`
  end

  exit
end

require "./lib/runner"

## ARGV can be provided in any order, [year, day, lang] being distinct.

# Extract language, default all
lang = ARGV.detect { |v| v =~ /^[a-z]+/ }
ARGV.delete(lang)
ext = lang ? Runner::LANG_EXTENSION[lang] : "*"

# Extract year, default latest
year = ARGV.detect { |v| v =~ /\A2[0-9]{3}\z/ }
ARGV.delete(year)
year ||= "*" # Dir["20*"].last

# Extract day, default whole-year
day = ARGV.detect { |v| v =~ /\A\d?\d\z/ }
day = "0#{day}" if day && day.to_i < 10
day = "*" if day.nil?

# Scan all relevant files to assemble row/column headers
runners = Dir["#{year}/#{day}/*.#{ext}"].map { |script| Runner.for(script) }.compact
langs = runners.map(&:lang).sort.uniq
dates = runners.map { |runner| [runner.year, runner.day] }.sort.uniq

totals = {}
# Render table
puts "Date       " + langs.map { |lang| "%10s" % lang }.join(" ")

thread_pool = Concurrent::Throttle.new(Concurrent.processor_count - 1)
results = {}
# Fork all processes
dates.each do |year, day|
  runs = langs.map do |lang|
    results[[year, day, lang]] = thread_pool.future do
      Runner.find(year, day, lang).run
    end
  end
end

runs = []
# Collect values, output table
dates.each do |year, day|
  runs = langs.map do |lang|
    results[[year, day, lang]].value.tap do |run|
      next if run.nil?
      totals[lang] ||= 0.0
      run.write! if ARGV.include?("--save")
      totals[lang] += run.duration
    end
  end.compact

  date = ("%4d-%02d" % [year, day]).ljust(10)
  puts [date, runs.map(&:success_duration_s)].flatten.join(" ")
end

if dates.size > 1
  puts
  # Render Summary
  puts "           " + langs.map { |lang| "%10s" % lang }.join(" ")
  puts "Total Time:" + langs.map { |lang| "%9.2fs" % totals[lang] }.join(" ")
else
  puts
  puts runs.map(&:solutions)
end
